repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: bash -c 'cd backend && poetry shell && poetry run black src'
        language: system

-   repo: local
    hooks:
    -   id: isort
        name: isort
        files: "\\.(py)$"
        entry: bash -c 'cd backend && poetry run isort src'
        language: system

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: bash -c 'cd backend && poetry run flake8 src'
        always_run: true
        language: system
