# Generated by Django 4.0.4 on 2022-05-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="box_state",
            field=models.CharField(
                choices=[("OP", "Open"), ("DU", "During"), ("CO", "Completed")], default="OP", max_length=2
            ),
        ),
    ]
