# Generated by Django 4.0.4 on 2022-05-18 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="box_state",
            field=models.CharField(
                choices=[("OP", "Open"), ("DU", "During"), ("CO", "Completed")],
                default="OP",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.user",
            ),
        ),
    ]
