# Generated by Django 4.0.4 on 2022-05-15 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_box_box_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_from",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.user"),
        ),
    ]
